# Generated by Django 5.2.7 on 2026-04-08 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Berita')),
                ('content', models.TextField(verbose_name='Isi Berita')),
                ('image', models.ImageField(blank=True, null=True, upload_to='berita_images/', verbose_name='Gambar')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Publikasi')),
            ],
            options={
                'verbose_name_plural': 'Berita',
                'ordering': ['-published_date'],
            },
        ),
    ]
